/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  javaBaseSidebar:[{type: 'autogenerated', dirName: 'java'}],
  netWorkSidebar:[{type: 'autogenerated', dirName: 'network'}],
  algorithmSidebar:[{type: 'autogenerated', dirName: 'algorithm'}],
  operationSystemSidebar:[{type: 'autogenerated', dirName: 'operationSystem'}],
  mysqlSidebar:[{type: 'autogenerated', dirName: 'mysql'}],
  redisSidebar:[{type: 'autogenerated', dirName: 'redis'}],
  springSidebar:[{type: 'autogenerated', dirName: 'spring'}],
  springBootSidebar:[{type: 'autogenerated', dirName: 'springBoot'}],
  springMvcSidebar:[{type: 'autogenerated', dirName: 'springMvc'}],
  myBatisSidebar:[{type: 'autogenerated', dirName: 'MyBatis'}],
  distributedSidebar:[{type: 'autogenerated', dirName: 'distributed'}],
  RPCSidebar:[{type: 'autogenerated', dirName: 'RPC'}],
  zooKeeperSidebar:[{type: 'autogenerated', dirName: 'zooKeeper'}],
  highPerformanceSidebar:[{type: 'autogenerated', dirName: 'highPerformance'}],
  highAvailabilitySidebar:[{type: 'autogenerated', dirName: 'highAvailability'}],
  projectSidebar:[{type: 'autogenerated', dirName: 'project'}],
  sceneDesignSidebar:[{type: 'autogenerated', dirName: 'sceneDesign'}],
  kafkaSidebar:[{type: 'autogenerated', dirName: 'kafka'}],
  nettySidebar:[{type: 'autogenerated', dirName: 'netty'}],
  linuxSidebar:[{type: 'autogenerated', dirName: 'linux'}],




  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
